services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: